# Generated by Django 5.0.7 on 2024-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100, verbose_name='操作')),
                ('result', models.CharField(max_length=100, verbose_name='结果')),
            ],
        ),
    ]
