# Generated by Django 5.0.7 on 2024-07-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='example',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shortcut.category', verbose_name='カテゴリ'),
        ),
    ]
